name: test_feature
description: A repo for test packages & features

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.2
  date_field: ^3.0.5
  flutter_timezone: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    # FaNum fonts
    - family: YekanBakhFaNumHairline
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_01_Hairline.ttf
    - family: YekanBakhFaNumThin
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_02_Thin.ttf
    - family: YekanBakhFaNumLight
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_03_Light.ttf
    - family: YekanBakhFaNumRegular
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_04_Regular.ttf
    - family: YekanBakhFaNumMedium
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_05_Medium.ttf
    - family: YekanBakhFaNumBold
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_06_Bold.ttf
    - family: YekanBakhFaNumHeavy
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_07_Heavy.ttf
    - family: YekanBakhFaNumFat
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_08_Fat.ttf

